# 主配置

server:
  port: 21106
  servlet:
    context-path: /supbuilder
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: default
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.202:3306/jeecg_boot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: Atcmis-123456
  redis:
    database: 11
    host: 192.168.100.202
    port: 6379
    password: ''
    lettuce:
      pool:
        max-active: 8   #最没大连接数据库连接数,设 0 为有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制



# mybatisPlus
mybatis-plus:
  # 开启mybatisPlus日志（输出到控制台）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    db-config:
      # 主键ID生成策略
      id-type: auto
      # 逻辑删除策略
      logic-delete-field: hide
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.supbuilder.user.service.domain
  mapper-locations: classpath:com/supbuilder/user/**/*.xml

supbuilder:

  converse:
    upload:
      path: C:\Users\矫克清\Desktop\converse\upload\
    result:
      path: C:\Users\矫克清\Desktop\converse\result\
    download:
      url: /usr/local/
